### your site title here

title: Henry Coles
description: 

baseurl: #name of GitHub repository
url: #custom url to be used instead of GitHub repository
email: #

# Pagination
paginate: 4
permalink: /news/:year/:title/
paginate_path: /news/page:num/

# Social media links in footer
twitter: "_pitest"
linkedin: "henry-coles-474ab93"
stackoverflow: "#"
github: "#"
researchgate: "#"
orcid: "#"
quora: "#"
instagram: "#"
facebook: "#"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  books:
    output: true
    permalink: /books/:name/
    order:
      - the_cipher_engines.md
      - the_traitors_moon.md
      - the_stowaway.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
